USE RetailDynamicsDB;

INSERT INTO Products (ProductName, Category, Subcategory, UnitPrice, Description) VALUES
('Camiseta Algodón Talla M', 'Ropa', 'Casual', 25.99, 'Camiseta de algodón suave, talla mediana.'),
('Pantalón Jeans Recto Talla 32', 'Ropa', 'Casual', 59.99, 'Pantalón vaquero corte recto, talla 32.'),
('Zapatillas Deportivas Hombre Talla 42', 'Calzado', 'Deportivo', 89.99, 'Zapatillas para correr de alto rendimiento, talla 42.'),
('Libro "La Sombra del Viento"', 'Libros', 'Ficción', 19.95, 'Novela de misterio y romance.'),
('Cafetera Eléctrica 12 Tazas', 'Electrodomésticos', 'Cocina', 45.75, 'Cafetera con capacidad para 12 tazas, programable.'),
('Mochila Deportiva 25L', 'Deportes', 'Accesorios', 35.50, 'Mochila resistente para actividades deportivas.'),
('Smartphone Android 6.5"', 'Electrónica', 'Móviles', 299.00, 'Smartphone con pantalla de 6.5 pulgadas y cámara de alta resolución.'),
('Auriculares Inalámbricos Bluetooth', 'Electrónica', 'Audio', 79.99, 'Auriculares inalámbricos con cancelación de ruido.'),
('Juego de Sábanas Queen Algodón', 'Hogar', 'Textil Hogar', 49.50, 'Juego de sábanas de algodón de 300 hilos para cama queen.'),
('Toalla de Baño Grande 100% Algodón', 'Hogar', 'Textil Hogar', 15.75, 'Toalla de baño grande y absorbente de algodón.'),
('Pelota de Fútbol Profesional', 'Deportes', 'Balones', 29.99, 'Pelota de fútbol reglamentaria para competición.'),
('Raqueta de Tenis Adulto', 'Deportes', 'Raquetas', 65.00, 'Raqueta de tenis de grafito para jugadores avanzados.'),
('Smartwatch Deportivo GPS', 'Electrónica', 'Wearables', 129.99, 'Reloj inteligente con GPS y monitor de frecuencia cardíaca.'),
('Tablet Android 10"', 'Electrónica', 'Tabletas', 199.00, 'Tablet con pantalla de 10 pulgadas y buena autonomía.'),
('Taza de Cerámica Diseño Floral', 'Hogar', 'Menaje', 8.99, 'Taza de cerámica con un diseño floral elegante.'),
('Set de Cubiertos Acero Inoxidable (24 piezas)', 'Hogar', 'Menaje', 39.99, 'Juego de cubiertos para 6 personas de acero inoxidable.'),
('Mouse Inalámbrico Ergonómico', 'Electrónica', 'Periféricos', 22.50, 'Ratón inalámbrico diseñado para la comodidad.'),
('Teclado Mecánico Gaming RGB', 'Electrónica', 'Periféricos', 119.00, 'Teclado mecánico con retroiluminación RGB personalizable.'),
('Sartén Antiadherente 24cm', 'Electrodomésticos', 'Cocina', 29.99, 'Sartén con revestimiento antiadherente de alta calidad.'),
('Olla a Presión 6 Litros', 'Electrodomésticos', 'Cocina', 75.00, 'Olla a presión de acero inoxidable con capacidad de 6 litros.'),
('Libro "Cien Años de Soledad"', 'Libros', 'Ficción', 15.50, 'Obra maestra de la literatura latinoamericana.'),
('Libro de Cocina Vegana', 'Libros', 'No Ficción', 22.00, 'Recetas deliciosas y saludables para una dieta vegana.'),
('Cargador Portátil 10000mAh', 'Electrónica', 'Accesorios', 28.75, 'Batería externa de alta capacidad para cargar dispositivos móviles.'),
('Cable USB-C a USB-A (1 metro)', 'Electrónica', 'Accesorios', 9.99, 'Cable de carga y transferencia de datos USB-C a USB-A.'),
('Gorra de Béisbol Algodón', 'Ropa', 'Accesorios', 18.50, 'Gorra de béisbol de algodón con visera.'),
('Bufanda de Lana Invierno', 'Ropa', 'Accesorios', 29.99, 'Bufanda de lana suave y cálida para el invierno.'),
('Balón de Baloncesto Oficial', 'Deportes', 'Balones', 39.99, 'Balón de baloncesto de tamaño y peso oficial.'),
('Gafas de Sol Polarizadas Hombre', 'Accesorios', 'Gafas', 55.00, 'Gafas de sol con lentes polarizadas para proteger de los rayos UV.'),
('Cartera de Cuero Hombre', 'Accesorios', 'Carteras', 42.50, 'Cartera de cuero genuino con múltiples compartimentos.'),
('Cinturón de Cuero Mujer', 'Accesorios', 'Cinturones', 32.00, 'Cinturón de cuero elegante para mujer.'),
('Pantalón Deportivo Hombre', 'Ropa', 'Deportivo', 45.00, 'Pantalón deportivo cómodo para entrenamiento.'),
('Blusa de Seda Mujer', 'Ropa', 'Formal', 39.99, 'Blusa elegante de seda para ocasiones especiales.'),
('Falda Midi Algodón', 'Ropa', 'Casual', 32.50, 'Falda de algodón de largo midi, ideal para el día a día.'),
('Zapatos de Vestir Hombre Cuero', 'Calzado', 'Formal', 79.99, 'Zapatos de cuero clásicos para vestir.'),
('Sandalias de Playa Mujer', 'Calzado', 'Casual', 29.99, 'Sandalias cómodas para la playa o piscina.'),
('Botas de Montaña Impermeables', 'Calzado', 'Deportivo', 119.00, 'Botas resistentes e impermeables para senderismo.'),
('Novela de Ciencia Ficción "Dune"', 'Libros', 'Ficción', 25.00, 'Clásico de la ciencia ficción.'),
('Libro de Historia "Sapiens"', 'Libros', 'No Ficción', 28.50, 'Un recorrido por la historia de la humanidad.'),
('Tostadora Eléctrica 2 Rebanadas', 'Electrodomésticos', 'Cocina', 29.99, 'Tostadora con 7 niveles de tostado.'),
('Batidora de Mano Inmersión', 'Electrodomésticos', 'Cocina', 35.75, 'Batidora de mano potente y versátil.'),
('Cámara Deportiva 4K', 'Electrónica', 'Cámaras', 149.00, 'Cámara de acción con resolución 4K y resistente al agua.'),
('Trípode para Cámara Ajustable', 'Electrónica', 'Accesorios', 25.50, 'Trípode ligero y ajustable para cámaras y smartphones.'),
('Funda Protectora para Smartphone', 'Electrónica', 'Accesorios', 15.99, 'Funda resistente a golpes para smartphone.'),
('Protector de Pantalla Vidrio Templado', 'Electrónica', 'Accesorios', 9.99, 'Protector de pantalla de vidrio templado de alta dureza.'),
('Almohada Viscoelástica Ergonómica', 'Hogar', 'Textil Hogar', 35.00, 'Almohada que se adapta a la forma del cuello para un mejor descanso.'),
('Manta Polar Suave Queen', 'Hogar', 'Textil Hogar', 29.75, 'Manta polar suave y cálida para cama queen.'),
('Cuchillo de Cocina Chef Acero Inoxidable', 'Hogar', 'Menaje', 19.99, 'Cuchillo de chef profesional de acero inoxidable.'),
('Tabla de Cortar Bambú', 'Hogar', 'Menaje', 14.50, 'Tabla de cortar ecológica de bambú.'),
('Monitor LED 24"', 'Electrónica', 'Periféricos', 179.00, 'Monitor de computadora con resolución Full HD.'),
('Impresora Multifunción Inalámbrica', 'Electrónica', 'Periféricos', 89.00, 'Impresora que escanea, copia e imprime de forma inalámbrica.'),
('Novela de Misterio "El Código Da Vinci"', 'Libros', 'Ficción', 18.75, 'Best-seller de misterio y suspense.'),
('Libro de Autoayuda "Los 7 Hábitos de la Gente Altamente Efectiva"', 'Libros', 'No Ficción', 21.00, 'Libro clásico de desarrollo personal.'),
('Power Bank Solar 20000mAh', 'Electrónica', 'Accesorios', 39.99, 'Cargador portátil que se recarga con energía solar.'),
('Cable HDMI 2.0 (2 metros)', 'Electrónica', 'Accesorios', 12.50, 'Cable HDMI de alta velocidad para conectar dispositivos.'),
('Camisa de Lino Hombre Manga Corta', 'Ropa', 'Casual', 38.00, 'Camisa de lino fresca y cómoda para el verano.'),
('Pantalones Cortos Deportivos Mujer', 'Ropa', 'Deportivo', 28.99, 'Pantalones cortos ideales para hacer ejercicio.'),
('Gafas de Lectura +2.0', 'Accesorios', 'Gafas', 19.50, 'Gafas de lectura con aumento de +2.0 dioptrías.'),
('Paraguas Plegable Automático', 'Accesorios', 'Paraguas', 22.00, 'Paraguas compacto y fácil de usar con apertura automática.'),
('Bicicleta de Montaña Aro 29"', 'Deportes', 'Bicicletas', 299.00, 'Bicicleta de montaña con cuadro de aluminio y cambios Shimano.'),
('Casco de Bicicleta Ajustable', 'Deportes', 'Accesorios', 45.00, 'Casco de seguridad para ciclismo con buena ventilación.'),
('Juego de Toallas de Mano (2 unidades)', 'Hogar', 'Textil Hogar', 12.99, 'Set de dos toallas de mano suaves y absorbentes.'),
('Juego de Cama Individual Microfibra', 'Hogar', 'Textil Hogar', 39.00, 'Juego de sábanas de microfibra suave para cama individual.'),
('Exprimidor de Cítricos Eléctrico', 'Electrodomésticos', 'Cocina', 32.50, 'Exprimidor eléctrico para naranjas, limones y otras frutas.'),
('Báscula de Cocina Digital', 'Electrodomésticos', 'Cocina', 18.75, 'Báscula de cocina precisa con pantalla LCD.'),
('Tarjeta de Memoria microSD 64GB', 'Electrónica', 'Almacenamiento', 15.50, 'Tarjeta de memoria de alta velocidad para dispositivos móviles.'),
('Disco Duro Externo 1TB USB 3.0', 'Electrónica', 'Almacenamiento', 69.00, 'Disco duro portátil de gran capacidad con conexión rápida.'),
('Bolso de Mano Mujer Elegante', 'Accesorios', 'Bolsos', 55.00, 'Bolso de mano sofisticado para eventos especiales.'),
('Cinturón de Cuero Trenzado Hombre', 'Accesorios', 'Cinturones', 38.50, 'Cinturón de cuero con diseño trenzado.'),
('Esterilla de Yoga Antideslizante', 'Deportes', 'Accesorios', 29.99, 'Mat de yoga con superficie antideslizante para mayor seguridad.'),
('Bandas de Resistencia (Set de 5)', 'Deportes', 'Accesorios', 24.00, 'Juego de bandas elásticas con diferentes niveles de resistencia.');