USE RetailDynamicsDB;

-- Insert 60 customers into the Customers table
INSERT INTO Customers (FirstName, LastName, Email, Phone, City, Country) VALUES
('Juan', 'Pérez', 'juan.perez@example.com', '555-1234', 'Ciudad de México', 'México'),
('María', 'Gómez', 'maria.gomez@example.com', '555-5678', 'Bogotá', 'Colombia'),
('Carlos', 'Rodríguez', 'carlos.rodriguez@example.com', '555-9012', 'Buenos Aires', 'Argentina'),
('Ana', 'López', 'ana.lopez@example.com', '555-3456', 'Santiago', 'Chile'),
('Pedro', 'Martínez', 'pedro.martinez@example.com', '555-7890', 'Lima', 'Perú'),
('Luisa', 'Fernández', 'luisa.fernandez@example.com', '555-2345', 'Caracas', 'Venezuela'),
('Diego', 'García', 'diego.garcia@example.com', '555-6789', 'Montevideo', 'Uruguay'),
('Sofía', 'Hernández', 'sofia.hernandez@example.com', '555-0123', 'Quito', 'Ecuador'),
('Javier', 'Díaz', 'javier.diaz@example.com', '555-4567', 'La Paz', 'Bolivia'),
('Isabel', 'Ruiz', 'isabel.ruiz@example.com', '555-8901', 'Asunción', 'Paraguay'),
('Andrés', 'Ramírez', 'andres.ramirez@example.com', '555-1122', 'Guadalajara', 'México'),
('Carolina', 'Torres', 'carolina.torres@example.com', '555-3344', 'Medellín', 'Colombia'),
('Sebastián', 'Flores', 'sebastian.flores@example.com', '555-5566', 'Rosario', 'Argentina'),
('Valentina', 'Silva', 'valentina.silva@example.com', '555-7788', 'Valparaíso', 'Chile'),
('Martín', 'Castro', 'martin.castro@example.com', '555-9900', 'Cusco', 'Perú'),
('Daniela', 'Jiménez', 'daniela.jimenez@example.com', '555-2233', 'Valencia', 'Venezuela'),
('Alejandro', 'Pérez', 'alejandro.perez@example.com', '555-6677', 'Maldonado', 'Uruguay'),
('Natalia', 'Sánchez', 'natalia.sanchez@example.com', '555-8899', 'Cuenca', 'Ecuador'),
('Oscar', 'González', 'oscar.gonzalez@example.com', '555-0011', 'Sucre', 'Bolivia'),
('Paula', 'Rodríguez', 'paula.rodriguez@example.com', '555-4455', 'Encarnación', 'Paraguay'),
('Miguel', 'López', 'miguel.lopez@example.com', '555-1212', 'Monterrey', 'México'),
('Gabriela', 'Gómez', 'gabriela.gomez@example.com', '555-3434', 'Cali', 'Colombia'),
('Fernando', 'Martínez', 'fernando.martinez@example.com', '555-5656', 'Córdoba', 'Argentina'),
('Constanza', 'Fernández', 'constanza.fernandez@example.com', '555-7878', 'Concepción', 'Chile'),
('Ricardo', 'Díaz', 'ricardo.diaz@example.com', '555-9090', 'Arequipa', 'Perú'),
('Carolina', 'Castro', 'carolina.castro@example.com', '555-2323', 'Barquisimeto', 'Venezuela'),
('Andrés', 'Jiménez', 'andres.jimenez@example.com', '555-6767', 'Punta del Este', 'Uruguay'),
('Valeria', 'Ruiz', 'valeria.ruiz@example.com', '555-8989', 'Ambato', 'Ecuador'),
('Diego', 'Ramírez', 'diego.ramirez@example.com', '555-0101', 'Oruro', 'Bolivia'),
('Ximena', 'Torres', 'ximena.torres@example.com', '555-4545', 'Ciudad del Este', 'Paraguay'),
('José', 'Pérez', 'jose.perez@example.com', '555-1357', 'Tijuana', 'México'),
('Daniela', 'Gómez', 'daniela.gomez@example.com', '555-2468', 'Barranquilla', 'Colombia'),
('Alejandro', 'Rodríguez', 'alejandro.rodriguez@example.com', '555-3579', 'Mendoza', 'Argentina'),
('Camila', 'López', 'camila.lopez@example.com', '555-4680', 'Temuco', 'Chile'),
('Esteban', 'Martínez', 'esteban.martinez@example.com', '555-5791', 'Trujillo', 'Perú'),
('Fiorella', 'Fernández', 'fiorella.fernandez@example.com', '555-6802', 'Ciudad Guayana', 'Venezuela'),
('Gabriel', 'García', 'gabriel.garcia@example.com', '555-7913', 'Salto', 'Uruguay'),
('Isabella', 'Hernández', 'isabella.hernandez@example.com', '555-8024', 'Riobamba', 'Ecuador'),
('Kevin', 'Díaz', 'kevin.diaz@example.com', '555-9135', 'Potosí', 'Bolivia'),
('Laura', 'Ruiz', 'laura.ruiz@example.com', '555-0246', 'Pedro Juan Caballero', 'Paraguay'),
('David', 'Ramírez', 'david.ramirez@example.com', '555-1470', 'Puebla', 'México'),
('Andrea', 'Torres', 'andrea.torres@example.com', '555-2581', 'Cartagena', 'Colombia'),
('Santiago', 'Flores', 'santiago.flores@example.com', '555-3692', 'Salta', 'Argentina'),
('Juliana', 'Silva', 'juliana.silva@example.com', '555-4703', 'Osorno', 'Chile'),
('Renato', 'Castro', 'renato.castro@example.com', '555-5814', 'Iquitos', 'Perú'),
('Valeria', 'Jiménez', 'valeria.jimenez@example.com', '555-6925', 'Puerto Ordaz', 'Venezuela'),
('Adrián', 'Pérez', 'adrian.perez@example.com', '555-8036', 'Paysandú', 'Uruguay'),
('Camila', 'Sánchez', 'camila.sanchez@example.com', '555-9147', 'Loja', 'Ecuador'),
('Emilio', 'González', 'emilio.gonzalez@example.com', '555-0258', 'Tarija', 'Bolivia'),
('Fernanda', 'Rodríguez', 'fernanda.rodriguez@example.com', '555-1369', 'Concepción', 'Paraguay'),
('Luis', 'López', 'luis.lopez@example.com', '555-2470', 'Querétaro', 'México'),
('Cecilia', 'Gómez', 'cecilia.gomez@example.com', '555-3581', 'Santa Marta', 'Colombia'),
('Héctor', 'Martínez', 'hector.martinez@example.com', '555-4692', 'Tucumán', 'Argentina'),
('Daniela', 'Fernández', 'daniela.fernandez@example.com', '555-5703', 'Puerto Montt', 'Chile'),
('Oscar', 'Díaz', 'oscar.diaz@example.com', '555-6814', 'Chiclayo', 'Perú'),
('Natalie', 'Castro', 'natalie.castro@example.com', '555-7925', 'Ciudad Bolívar', 'Venezuela'),
('Sergio', 'Jiménez', 'sergio.jimenez@example.com', '555-8037', 'Rivera', 'Uruguay'),
('Tatiana', 'Ruiz', 'tatiana.ruiz@example.com', '555-9148', 'Esmeraldas', 'Ecuador'),
('Víctor', 'Ramírez', 'victor.ramirez@example.com', '555-0259', 'Cobija', 'Bolivia'),
('Zulma', 'Torres', 'zulma.torres@example.com', '555-1370', 'Caacupé', 'Paraguay')
